# Trains the Thermal-UDE neural network heat-generation model, following
# CLAUDE.md's governing equation, network architecture, and training /
# validation condition split for Case 1 and Case 2. Case 2 warm-starts
# from Case 1's optimized parameters. Optimization is a two-stage
# ADAM -> BFGS procedure (SciML/DiffEqFlux UDE training pattern).
#
# Usage:
#   julia --project=. train.jl 1     # train Case 1 (cold start)
#   julia --project=. train.jl 2     # train Case 2 (warm-started from Case 1)
#
# Iteration budgets can be overridden via environment variables
# (UDE_ADAM_ITERS, UDE_BFGS_ITERS, UDE_ADAM_LR) for a full reproduction
# run; the defaults below are kept modest so CI finishes quickly.

using DifferentialEquations, Lux
using JLD2, Plots, StableRNGs, Statistics
using ComponentArrays, Interpolations
using MAT
using Optimization, OptimizationOptimisers, OptimizationOptimJL
using SciMLSensitivity
using Zygote

const ADAM_ITERS = parse(Int, get(ENV, "UDE_ADAM_ITERS", "200"))
const BFGS_ITERS = parse(Int, get(ENV, "UDE_BFGS_ITERS", "50"))
const ADAM_LR    = parse(Float64, get(ENV, "UDE_ADAM_LR", "0.01"))

# function to find the end of the discharge in the constant current discharge tests.
function find_discharge_end(Current_data, start=5)
    for i in start:length(Current_data)
        if abs(Current_data[i]) == 0
            return i
        end
    end
    return -1
end

# function to get the current value for the constant current discharge tests
function current_val(Crate)
    if Crate == "0p5C"
        return 0.5 * 5.0
    elseif Crate == "1C"
        return 1.0 * 5.0
    elseif Crate == "2C"
        return 2.0 * 5.0
    elseif Crate == "1p5C"
        return 1.5 * 5.0
    end
end

# Loads one condition's time/temperature/current series from a case's Dataset.jld2.
function load_data(data_file, name1::String, name2::Int64)
    if name1 == "WLTP"
        data = data_file["$(name1)_T$(name2)"]
        t_raw = data["time"]
        T_raw = data["temperature"]
        current_raw = data["current"]

        first_indices = unique(idx -> t_raw[idx], eachindex(t_raw))
        t = t_raw[first_indices]
        T = T_raw[first_indices]
        current = current_raw[first_indices]
        I = LinearInterpolation(t, current, extrapolation_bc=Interpolations.Flat())
        T∞ = T[1]
        SOC0 = 0.9
        return t, T, T∞, I, SOC0
    else
        data = data_file["$(name1)_T$(name2)"]
        n = find_discharge_end(data["current"])
        t_raw = data["time"][2:n]
        T_raw = data["temperature"][2:n]

        first_indices = unique(idx -> t_raw[idx], eachindex(t_raw))
        t = t_raw[first_indices]
        T = T_raw[first_indices]

        I0 = current_val(name1)
        current_const = fill(I0, length(t))
        I = LinearInterpolation(t, current_const, extrapolation_bc=Interpolations.Flat())

        T∞ = T[1]
        SOC0 = 1.0
        return t, T, T∞, I, SOC0
    end
end

# The UDE model: known SOC (Coulomb-counting) physics + NN-estimated heat
# generation G = U([SOC, T, I], p)^2 driving the lumped thermal ODE.
function UDE_model!(du, u, p, t, T∞, I_func, U, st)
    Cbat = 5 * 3600
    I = I_func(t)
    du[1] = -I / Cbat

    C₁ = -0.00153
    C₂ = 0.020306 # Thermal parameters

    G = (U([u[1], u[2], I], p, st)[1][1])^2 # The heat generated by the battery cell
    du[2] = (C₁ * (u[2] - T∞)) + (C₂ * G)   # The lumped thermal model of the battery cell
end

rmse(y, ŷ) = sqrt(mean(abs2, y .- ŷ))
mae(y, ŷ) = mean(abs, y .- ŷ)
function r2_score(y, ŷ)
    ss_res = sum(abs2, y .- ŷ)
    ss_tot = sum(abs2, y .- mean(y))
    return 1 - ss_res / ss_tot
end

# Training / validation conditions per CLAUDE.md (Crate, ambient temperature °C).
const CASE_TRAIN_CONDITIONS = Dict(
    1 => [("0p5C", 0), ("0p5C", 25), ("1C", 10), ("1C", 25), ("2C", 0), ("2C", 10)],
    2 => [("0p5C", 0), ("WLTP", 10), ("2C", 25), ("0p5C", 25), ("WLTP", 0), ("1C", 10)],
)

const CASE_VAL_CONDITIONS = Dict(
    1 => [("0p5C", 10), ("1C", 0), ("2C", 25), ("WLTP", 0), ("WLTP", 10), ("WLTP", 25)],
    2 => [("0p5C", 10), ("1C", 0), ("1C", 25), ("2C", 0), ("2C", 10), ("WLTP", 25)],
)

struct Condition
    label::String
    prob::ODEProblem
    t::Vector{Float64}
    T::Vector{Float64}
end

function condition_label(crate, temp)
    c = replace(crate, "p" => ".")
    c = replace(c, "C" => " C")
    return "$(c), $(temp)°C"
end

function build_conditions(conditions, data_file, U, st)
    result = Condition[]
    for (crate, temp) in conditions
        t, T, T∞, I, SOC0 = load_data(data_file, crate, temp)
        model!(du, u, p, tt) = UDE_model!(du, u, p, tt, T∞, I, U, st)
        prob = ODEProblem(model!, [SOC0, T∞], (t[1], t[end]), nothing)
        push!(result, Condition(condition_label(crate, temp), prob, collect(Float64, t), collect(Float64, T)))
    end
    return result
end

# Loss summed across the mixed set of training conditions for this case.
function total_loss(p, conditions, Solver)
    total = 0.0
    n = 0
    for c in conditions
        sol = solve(remake(c.prob, p=p), Solver, saveat=c.t,
                    sensealg=InterpolatingAdjoint(autojacvec=ZygoteVJP()))
        if length(sol.t) != length(c.t)
            return Inf
        end
        pred = Array(sol)[2, :]
        total += sum(abs2, pred .- c.T)
        n += length(c.T)
    end
    return total / n
end

function evaluate(conditions, p, Solver)
    metrics = NamedTuple[]
    for c in conditions
        sol = solve(remake(c.prob, p=p), Solver, saveat=c.t)
        pred_C = Array(sol)[2, :] .- 273.15
        meas_C = c.T .- 273.15
        push!(metrics, (
            condition = c.label,
            rmse = rmse(meas_C, pred_C),
            mae = mae(meas_C, pred_C),
            r2 = r2_score(meas_C, pred_C),
        ))
    end
    return metrics
end

function plot_conditions(conditions, p, Solver, out_path, title_prefix)
    n = length(conditions)
    ncols = 2
    nrows = ceil(Int, n / ncols)
    P = plot(layout=(nrows, ncols), size=(900, 350 * nrows), dpi=300, framestyle=:box)
    for (i, c) in enumerate(conditions)
        sol = solve(remake(c.prob, p=p), Solver, saveat=c.t)
        pred_C = Array(sol)[2, :] .- 273.15
        meas_C = c.T .- 273.15
        t_hours = (c.t .- c.t[1]) ./ 3600

        plot!(P[i], t_hours, meas_C, label="Measured", color=:black, linewidth=1.5)
        plot!(P[i], t_hours, pred_C, label="Predicted", color=:red, linewidth=1.5, linestyle=:dash)
        title!(P[i], "$(title_prefix): $(c.label)", titlefontsize=10)
        xlabel!(P[i], "Time (h)")
        ylabel!(P[i], "Temperature (°C)")
    end
    plot!(P, legend=:best, left_margin=5Plots.mm, bottom_margin=5Plots.mm, top_margin=3Plots.mm)
    savefig(P, out_path)
end

function train_case(case::Int)
    @assert case in (1, 2) "case must be 1 or 2"
    dataset_dir = joinpath(@__DIR__, "Case_$case")
    data_file = load(joinpath(dataset_dir, "Dataset.jld2"))["Dataset"]

    U = Lux.Chain(Lux.Dense(3, 20, tanh), Lux.Dense(20, 1))
    rng = StableRNG(1111)
    p_init, st = Lux.setup(rng, U)
    p0 = ComponentArray(p_init)

    if case == 2
        fresh_path = joinpath(@__DIR__, "results", "case1", "opt_para_case1_trained.jld2")
        shipped_path = joinpath(@__DIR__, "Case_1", "opt_para_case_1.jld2")
        if isfile(fresh_path)
            p0 = load(fresh_path)["opt_para_case1_trained"]
            println("Warm-starting Case 2 from freshly trained Case 1 parameters.")
        elseif isfile(shipped_path)
            p0 = load(shipped_path)["opt_para_case_1"]
            println("Warm-starting Case 2 from shipped Case 1 optimized parameters.")
        else
            error("No Case 1 optimized parameters found to warm-start Case 2.")
        end
    end

    train_conditions = build_conditions(CASE_TRAIN_CONDITIONS[case], data_file, U, st)
    val_conditions = build_conditions(CASE_VAL_CONDITIONS[case], data_file, U, st)

    Solver = Tsit5()
    loss(p, _) = total_loss(p, train_conditions, Solver)

    iter = Ref(0)
    function callback(state, l)
        iter[] += 1
        if iter[] % 25 == 0
            println("  iter $(iter[])  loss = $(l)")
        end
        return false
    end

    optf = OptimizationFunction(loss, Optimization.AutoZygote())

    println("== Case $case: Stage 1 (ADAM) ==")
    optprob1 = OptimizationProblem(optf, p0)
    res1 = Optimization.solve(optprob1, OptimizationOptimisers.Adam(ADAM_LR); maxiters=ADAM_ITERS, callback=callback)

    println("== Case $case: Stage 2 (BFGS) ==")
    optprob2 = OptimizationProblem(optf, res1.u)
    res2 = Optimization.solve(optprob2, OptimizationOptimJL.BFGS(); maxiters=BFGS_ITERS, callback=callback)

    p_opt = res2.u

    out_dir = joinpath(@__DIR__, "results", "case$case")
    mkpath(out_dir)

    save(joinpath(out_dir, "opt_para_case$(case)_trained.jld2"), "opt_para_case$(case)_trained", p_opt)

    metrics = evaluate(val_conditions, p_opt, Solver)
    open(joinpath(out_dir, "metrics_case$case.csv"), "w") do io
        println(io, "condition,rmse_C,mae_C,r2")
        for m in metrics
            println(io, "$(m.condition),$(m.rmse),$(m.mae),$(m.r2)")
        end
    end

    println("\nValidation metrics for Case $case:")
    for m in metrics
        println("  $(m.condition): RMSE=$(round(m.rmse, digits=4))°C  MAE=$(round(m.mae, digits=4))°C  R²=$(round(m.r2, digits=4))")
    end
    mean_r2 = mean(m.r2 for m in metrics)
    println("  Mean validation R² = $(round(mean_r2, digits=4))  (acceptance criterion: R² > 0.80)")

    plot_conditions(val_conditions, p_opt, Solver, joinpath(out_dir, "validation_case$case.png"), "Case $case")

    return p_opt, metrics
end

function main()
    if length(ARGS) != 1 || !(ARGS[1] in ("1", "2"))
        println("Usage: julia train.jl <1|2>")
        exit(1)
    end
    train_case(parse(Int, ARGS[1]))
end

main()
