# The required packages are imported. Please ensure you have them installed in your Julia environment before running the code.
using DifferentialEquations , Lux   
using JLD2 , Plots , StableRNGs , Statistics
using ComponentArrays , Interpolations
using MAT

# function to find the end of the discharge in the constant current discharge tests.
function find_discharge_end(Current_data,start=5)
    for i in start:length(Current_data)
        if abs(Current_data[i]) == 0
            return i 
        end
    end
    return -1 
end

#function to get the current value for the constant current discharge tests
function current_val(Crate)
    if Crate == "0p5C"
        return 0.5*5.0
    elseif Crate == "1C"
        return 1.0*5.0
    elseif Crate == "2C"
        return 2.0*5.0
    elseif Crate == "1p5C"
        return 1.5*5.0
    end
end

# load the data from the JLD2 file
data_file = load("Dataset.jld2")["Dataset"]

# Function to load the data from data_file
function load_data(name1::String,name2::Int64)
    if name1 == "WLTP"
        data = data_file["$(name1)_T$(name2)"]
        t_raw = data["time"]
        T_raw = data["temperature"]
        current_raw = data["current"]

        # Get indices of unique times
        first_indices = unique(idx -> t_raw[idx],eachindex(t_raw))
        t = t_raw[first_indices]
        T = T_raw[first_indices]
        current = current_raw[first_indices]
        I    = LinearInterpolation(t,current,extrapolation_bc=Interpolations.Flat())
        T∞ = T[1]
        SOC0   = 0.9
        return t,T,T∞,I,SOC0
    else
        data = data_file["$(name1)_T$(name2)"]
        n    = find_discharge_end(data["current"])
        t_raw = data["time"][2:n]
        T_raw = data["temperature"][2:n]
        
        
        first_indices = unique(idx -> t_raw[idx],eachindex(t_raw))

        t       = t_raw[first_indices]
        T       = T_raw[first_indices]
        
        I0 = current_val(name1)
        current_const = fill(I0,length(t))
        I = LinearInterpolation(t,current_const,extrapolation_bc = Interpolations.Flat())

        
        T∞     = T[1]
        SOC0   = 1.0
        return t,T,T∞,I,SOC0
    end
end

# Conditions to simulate. At a time 6 conditions can be simulated. 
# The Crates can take values of "0p5C", "1C", "2C" , "WLTP"
# Temp can take values of 0, 10, 25
Crate1,Temp1 = "2C",0
Crate2,Temp2 = "2C",10
Crate3,Temp3 = "2C",25
Crate4,Temp4 = "WLTP",0
Crate5,Temp5 = "WLTP",10
Crate6,Temp6 = "WLTP",25

t1,T1,T∞1,I1,SOC1_0     = load_data(Crate1,Temp1)
t2,T2,T∞2,I2,SOC2_0     = load_data(Crate2,Temp2)
t3,T3,T∞3,I3,SOC3_0     = load_data(Crate3,Temp3)
t4,T4,T∞4,I4,SOC4_0     = load_data(Crate4,Temp4)
t5,T5,T∞5,I5,SOC5_0     = load_data(Crate5,Temp5)
t6,T6,T∞6,I6,SOC6_0     = load_data(Crate6,Temp6)

#Defining the neural network
U = Lux.Chain(Lux.Dense(3,20,tanh),Lux.Dense(20,1))
rng = StableRNG(1111)
_para,st = Lux.setup(rng,U)
const _st_ = st

#Defining the UDE model
function UDE_model!(du,u,p,t,T∞,I_func)

    Cbat = 5*3600
    I = I_func(t)
    du[1] = -I/Cbat

    C₁ = -0.00153
    C₂ = 0.020306 #Thermal parameters

    G = (U([u[1],u[2],I],p,_st_)[1][1])^2 # The heat generated by the battery cell

    du[2] = (C₁*(u[2]-T∞)) + (C₂*G) # The lumped thermal model of the battery cell

end

UDE_model1!(du,u,p,t) = UDE_model!(du,u,p,t,T∞1,I1)
UDE_model2!(du,u,p,t) = UDE_model!(du,u,p,t,T∞2,I2)
UDE_model3!(du,u,p,t) = UDE_model!(du,u,p,t,T∞3,I3)
UDE_model4!(du,u,p,t) = UDE_model!(du,u,p,t,T∞4,I4)
UDE_model5!(du,u,p,t) = UDE_model!(du,u,p,t,T∞5,I5)
UDE_model6!(du,u,p,t) = UDE_model!(du,u,p,t,T∞6,I6)

# Defining the ODE problems for each dataset
prob1 = ODEProblem(UDE_model1!,[SOC1_0,T∞1],(t1[1],t1[end]),_para)
prob2 = ODEProblem(UDE_model2!,[SOC2_0,T∞2],(t2[1],t2[end]),_para)
prob3 = ODEProblem(UDE_model3!,[SOC3_0,T∞3],(t3[1],t3[end]),_para)
prob4 = ODEProblem(UDE_model4!,[SOC4_0,T∞4],(t4[1],t4[end]),_para)
prob5 = ODEProblem(UDE_model5!,[SOC5_0,T∞5],(t5[1],t5[end]),_para)
prob6 = ODEProblem(UDE_model6!,[SOC6_0,T∞6],(t6[1],t6[end]),_para)

# Load the trained parameters
para_opt = load("opt_para_case_1.jld2")["opt_para_case_1"]


"__________________plotting the results__________________"

problems = [prob1,prob2,prob3,prob4,prob5,prob6]
times = [t1,t2,t3,t4,t5,t6]
data = [T1,T2,T3,T4,T5,T6]
Temps = [Temp1,Temp2,Temp3,Temp4,Temp5,Temp6]
Crates = [Crate1,Crate2,Crate3,Crate4,Crate5,Crate6]

function condition_label(crate, temp)
    c = replace(crate, "p" => ".")  # "0p5C" → "0.5C", "1C" → "1C"
    c = replace(c, "C" => " C")     # "1 C", "0.5 C"
    return "$(c), $(temp)°C"
end

condition_labels = [condition_label(c, t) for (c, t) in zip(Crates, Temps)]
#solver
Solver = Tsit5()

default(
    fontfamily    = "Computer Modern",
    titlefontsize = 10,
    guidefontsize = 9,
    legendfontsize = 8,
    tickfontsize  = 8,
    dpi           = 300
)
P = plot(layout = (3,2), size = (900, 1000), dpi = 300, framestyle = :box)


# Plotting results
for i in 1:6
    prob = remake(problems[i],p=para_opt)
    sol = solve(prob,Solver,saveat = times[i])
    sol_array = Array(sol)[2,:]
    sol_degc = sol_array.-273.15
    data_degc = data[i].-273.15
    t_hours = (times[i].-times[i][1])./3600
    
    plot!(P[i],
        t_hours, data_degc,
        label     = "Measured",
        color     = :black,
        linewidth = 1.5,
        linestyle = :solid
    )
    plot!(P[i],
        t_hours, sol_degc,
        label     = "Predicted",
        color     = :red,
        linewidth = 1.5,
        linestyle = :dash
    )

    title!(P[i], condition_labels[i], titlefontsize = 10)
    xlabel!(P[i], "Time (h)", guidefontsize = 9)
    ylabel!(P[i], "Temperature (°C)", guidefontsize = 9)
    
end

plot!(P,
    legend       = :best,
    legendfontsize = 8,
    left_margin  = 5Plots.mm,
    bottom_margin = 5Plots.mm,
    top_margin   = 3Plots.mm
)

display(P)
plot!(P, dpi = 600)

savefig(P,"Thermal_UDE_Case1.png")




